In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    columns=[
        "hidden_dim",
        "epochs",
        "weight_decay",
        "lr",
        "batch_size",
        "youden",
    ]
)

selected_df = pd.DataFrame(
    columns=["Dataset", "hidden_dim", "epochs", "weight_decay", "lr", "batch_size", "youden"]
)

In [3]:
for line in open("../code/facebook_results.txt"):
    if not line.startswith("("):
        continue
    youden = float(line.split(" ")[-1])
    params = "".join(line.split(" ")[:-1])
    hidden_dim, epochs, weight_decay, lr, batch_size = eval(params)
    df.loc[len(df)] = [hidden_dim, epochs, weight_decay, lr, batch_size, youden]
df.sort_values("youden", ascending=False, inplace=True)
df.head(10)
selected = df.iloc[0]
selected["Dataset"] = "Facebook"
selected_df.loc[len(selected_df)] = selected

In [12]:
df = pd.DataFrame(
    columns=[
        "hidden_dim",
        "epochs",
        "weight_decay",
        "lr",
        "batch_size",
        "youden",
    ]
)

prev_selected = (2000,25,5.0,0.005, 32)
youden_prev_selected = None

for line in open("../code/synthetic_results.txt"):
    if not line.startswith("("):
        continue
    youden = float(line.split(" ")[-1])
    params = "".join(line.split(" ")[:-1])
    hidden_dim, epochs, weight_decay, lr, batch_size = eval(params)
    if (hidden_dim, epochs, weight_decay, lr, batch_size) == prev_selected:
        print("Previously selected, youden:", youden)
        youden_prev_selected = youden
    df.loc[len(df)] = [hidden_dim, epochs, weight_decay, lr, batch_size, youden]
df.sort_values("youden", ascending=False, inplace=True)
df.head(10)
selected = df.iloc[0]
selected["Dataset"] = "Synthetic"
selected_df.loc[len(selected_df)] = selected
if youden_prev_selected is not None and youden_prev_selected == selected["youden"]:
    print("The previously selected hyperparameters are still the best.")

Previously selected, youden: 0.22625
The previously selected hyperparameters are still the best.

In [ ]:
df = pd.DataFrame(
    columns=[
        "hidden_dim",
        "epochs",
        "weight_decay",
        "lr",
        "batch_size",
        "youden",
    ]
)


for line in open("../code/polluted_synthetic_results.txt"):
    if not line.startswith("("):
        continue
    youden = float(line.split(" ")[-1])
    params = "".join(line.split(" ")[:-1])
    hidden_dim, epochs, weight_decay, lr, batch_size = eval(params)
    df.loc[len(df)] = [hidden_dim, epochs, weight_decay, lr, batch_size, youden]
df.sort_values("youden", ascending=False, inplace=True)
df.head(10)
selected = df.iloc[0]
selected["Dataset"] = "Noisy Synthetic"
selected_df.loc[len(selected_df)] = selected

Previously selected, youden: 0.05653594771241821

In [7]:
df = pd.DataFrame(
    columns=[
        "hidden_dim",
        "epochs",
        "weight_decay",
        "lr",
        "batch_size",
        "youden",
    ]
)

for line in open("../code/brca_n_results.txt"):
    if not line.startswith("("):
        continue
    youden = float(line.split(" ")[-1])
    params = "".join(line.split(" ")[:-1])
    hidden_dim, epochs, weight_decay, lr, batch_size = eval(params)
    df.loc[len(df)] = [hidden_dim, epochs, weight_decay, lr, batch_size, youden]
df.sort_values("youden", ascending=False, inplace=True)
df.head(10)
selected = df.iloc[0]
selected["Dataset"] = "Brca_n"
selected_df.loc[len(selected_df)] = selected

In [8]:
selected_df

           Dataset hidden_dim epochs weight_decay     lr batch_size    youden
0         Facebook     2000.0  100.0         10.0  0.001       32.0  0.472771
1        Synthetic    10000.0   75.0         10.0  0.005       64.0   0.22625
2  Noisy Synthetic      500.0   50.0          5.0   0.01      128.0  0.208088
3           Brca_n    10000.0  100.0         10.0  0.005       64.0  0.956522

In [9]:
print(selected_df.to_markdown())

|    | Dataset         |   hidden_dim |   epochs |   weight_decay |    lr |   batch_size |   youden |
|---:|:----------------|-------------:|---------:|---------------:|------:|-------------:|---------:|
|  0 | Facebook        |         2000 |      100 |             10 | 0.001 |           32 | 0.472771 |
|  1 | Synthetic       |        10000 |       75 |             10 | 0.005 |           64 | 0.22625  |
|  2 | Noisy Synthetic |          500 |       50 |              5 | 0.01  |          128 | 0.208088 |
|  3 | Brca_n          |        10000 |      100 |             10 | 0.005 |           64 | 0.956522 |

In [11]:
df[df["youden"] == df["youden"].max()]

     hidden_dim  epochs  weight_decay     lr  batch_size   youden
670     10000.0    75.0          10.0  0.005        64.0  0.22625
669     10000.0    75.0          10.0  0.005        32.0  0.22625
645     10000.0    50.0          12.0  0.010        32.0  0.22625
652     10000.0    75.0           5.0  0.005        64.0  0.22625
653     10000.0    75.0           5.0  0.005       128.0  0.22625
..          ...     ...           ...    ...         ...      ...
716     10000.0   100.0          12.0  0.005       128.0  0.22625
715     10000.0   100.0          12.0  0.005        64.0  0.22625
684     10000.0   100.0           5.0  0.001        32.0  0.22625
671     10000.0    75.0          10.0  0.005       128.0  0.22625
672     10000.0    75.0          10.0  0.010        32.0  0.22625

[108 rows x 6 columns]