In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
# Generate list of length n with values 1 and 0 
def generate_list(n, alpha=0.99):
    if alpha == 1:
        return [1] * n
    # Generate a list of 1s and 0s
    lst = [1] * (int(n * alpha)+1) + [0] * (int(n * (1-alpha))+1)
    
    # Shuffle the list to randomize the order
    random.shuffle(lst)
    
    # Adjust the length of the list to n
    lst = lst[:n]
    return lst

In [3]:
def expand_csv(input_file, additional_cols=0, additional_cols_values=2, alpha=0.99):
    df = pd.read_csv(input_file, sep=";")
    df = df.fillna(0)

    cols = list(df.columns)
    cols.remove("Index")
    for col in cols:
        df[col] = df[col].astype(int)

    data = { c : [] for c in cols }

    for _, row in df.iterrows():
        try:
            start, end = map(int, row["Index"].split("-"))
        except ValueError:
            continue

        count = end - start
        for col in cols:
            if row[col] == 1:
                lst = generate_list(count, alpha)
                data[col].extend(lst)
            else:
                lst = [0] * count
                data[col].extend(lst)

    df_expanded = pd.DataFrame(data)

    if additional_cols == 0:
        return df_expanded
    new_cols = []
    new_col_names = []
    for i in range(additional_cols):
        col_name = f"col_{i+1}"
        lst = random.choices(range(additional_cols_values), k=len(df_expanded))
        new_cols.append(pd.Series(lst, name=col_name))
        new_col_names.append(col_name)
    df_expanded = pd.concat([df_expanded] + new_cols, axis=1, ignore_index=True)
    # Renombrar las columnas
    df_expanded.columns = cols + new_col_names
    return df_expanded

In [ ]:
input_file = "input3.csv"
df_expanded = expand_csv(input_file, additional_cols=2000, additional_cols_values=5, alpha=1)

In [5]:
df_expanded

,Target,Attribute 1,Attribute 2,Attribute 3,Attribute 4,Attribute 5,Attribute 6,col_1,col_2,col_3,...,col_1991,col_1992,col_1993,col_1994,col_1995,col_1996,col_1997,col_1998,col_1999,col_2000
0,1,1,1,1,0,0,0,0,3,2,...,2,2,4,4,0,1,3,2,2,0
1,1,1,1,1,0,0,0,4,4,2,...,4,1,1,0,0,0,4,1,1,0
2,1,1,1,1,0,0,0,0,2,2,...,1,4,0,4,1,0,0,2,3,0
3,1,1,1,1,0,0,0,2,0,1,...,2,3,0,3,0,3,0,4,1,4
4,1,1,1,1,0,0,0,3,2,3,...,3,2,0,2,2,4,1,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0,0,0,0,0,0,0,2,0,1,...,2,3,4,2,2,3,1,0,2,2
6996,0,0,0,0,0,0,0,1,1,4,...,2,2,0,3,2,3,2,2,3,0
6997,0,0,0,0,0,0,0,2,2,2,...,2,2,3,1,3,2,4,2,4,1
6998,0,0,0,0,0,0,0,4,2,1,...,4,1,1,4,3,1,3,4,1,3
6999,0,0,0,0,0,0,0,0,0,4,...,4,2,2,1,1,4,0,4,4,0

In [6]:
df_expanded.shape

(7000, 2007)

In [7]:
df_expanded.to_csv("../data/synthetic3.csv", index=False, sep=";")

In [ ]:
input_file = "input.csv"
df_expanded = expand_csv(input_file, additional_cols=2000, additional_cols_values=5, alpha=0.9)

In [ ]:
df_expanded

,Target,Attribute 1,Attribute 2,Attribute 3,Attribute 4,Attribute 5,Attribute 6,col_1,col_2,col_3,...,col_1991,col_1992,col_1993,col_1994,col_1995,col_1996,col_1997,col_1998,col_1999,col_2000
0,1,1,1,1,0,0,0,0,3,2,...,2,2,4,4,0,1,3,2,2,0
1,1,1,1,1,0,0,0,4,4,2,...,4,1,1,0,0,0,4,1,1,0
2,1,1,1,1,0,0,0,0,2,2,...,1,4,0,4,1,0,0,2,3,0
3,1,1,1,1,0,0,0,2,0,1,...,2,3,0,3,0,3,0,4,1,4
4,1,1,1,1,0,0,0,3,2,3,...,3,2,0,2,2,4,1,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0,0,0,0,0,0,0,2,0,1,...,2,3,4,2,2,3,1,0,2,2
6996,0,0,0,0,0,0,0,1,1,4,...,2,2,0,3,2,3,2,2,3,0
6997,0,0,0,0,0,0,0,2,2,2,...,2,2,3,1,3,2,4,2,4,1
6998,0,0,0,0,0,0,0,4,2,1,...,4,1,1,4,3,1,3,4,1,3
6999,0,0,0,0,0,0,0,0,0,4,...,4,2,2,1,1,4,0,4,4,0

In [ ]:
df_expanded.shape

(7000, 2007)

In [ ]:
df_expanded.to_csv("../data/synthetic3-5.csv", index=False, sep=";")